### ISSUE TITLE
Updated tauri-cli

### ISSUE THREAD

**Issue by lupyuen** [stevepryde/tauri-yew-demo#1]
Thanks for the awesome article :-) I had to tweak the installation of `tauri-cli` like so...

```bash
cargo install tauri-cli --git https://github.com/tauri-apps/tauri --branch next
```

(According to https://github.com/tauri-apps/tauri/issues/3050)

Here are the steps I used to run your demo on PinePhone...

https://gist.github.com/lupyuen/5566af817e964ecf25488e5cbe8c2ea1

Thanks again :-)

**Comment by stevepryde** [comment]
Nice :)

I've updated the article to mention the `tauri-cli` install issue. Was there anything else I needed to change from the article? I suspect your issue with trunk was likely related to the PinePhone ? Feel free to post your gist as a comment on the article if you want to share it

**Comment by lupyuen** [comment]
Yeah PinePhone has too little RAM, only 2GB :-) Everything else works great, just a little slow. Thanks! :-)
