### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by gdennie** [stevepryde/tauri-yew-demo#2]
Nice. However, I am not quite sure how to compile and also run your demo. Clearly I need to read more about `Tauri` but it would help if your docs include that information (the `Tauri` docs seem to also hide this info someplace).

Also, `cargo install tauri-cli --version ^1.0.0-beta` is failing with the docker `rust:1.58.1` image as a remote development environment resulting in the following messages (What version is compatible?):

```
   Compiling handlebars v4.2.1
   Compiling json-patch v0.2.6
   Compiling tauri-bundler v1.0.0-beta.4
   Compiling tauri-cli v1.0.0-beta.7
error[E0432]: unresolved import `clap::crate_version`
 --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tauri-cli-1.0.0-beta.7/src/main.rs:6:12
  |
6 | use clap::{crate_version, load_yaml, App, AppSettings, ArgMatches};
  |            ^^^^^^^^^^^^^ no `crate_version` in the root

error: cannot determine resolution for the macro `crate_version`
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tauri-cli-1.0.0-beta.7/src/main.rs:265:14
    |
265 |     .version(crate_version!())
    |              ^^^^^^^^^^^^^
    |
    = note: import resolution is stuck, try simplifying macro imports

error[E0308]: mismatched types
   --> /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/tauri-cli-1.0.0-beta.7/src/main.rs:264:23
    |
264 |   let app = App::from(yaml)
    |                       ^^^^ expected struct `App`, found `&yaml_rust::yaml::Yaml`
```

**Comment by rnice01** [comment]
I believe this is the same error you're dealing with. Linking the comment explaining what is causing it and the resolution is in the thread.
https://github.com/tauri-apps/tauri/issues/3050#issuecomment-989658552

**Comment by stevepryde** [comment]
Always check the official docs for how to install the Tauri CLI: https://tauri.studio/docs/getting-started/beginning-tutorial#alternatively-install-tauri-cli-as-a-cargo-subcommand

I've updated the dev.to article as well

**Comment by stevepryde** [comment]
Currently it looks like this:
```
cargo install tauri-cli --locked --version ^1.0.0-rc
```
