### ISSUE TITLE
Do you like to work with me on this project.

### ISSUE THREAD

**Issue by AlenSci** [stevepryde/tauri-yew-demo#8]
I am using your template for my project. It is a notion.so clone, But I am trying to enhance everything. For example, notion.so is a bit slow and take too much memory because they are using electron  while we can use tauri. [click here](https://github.com/AlenSci/autodox-tauri) to see my project, my discord id `Alisci#1598`. If you joined me I would pay U for your work. This is not just free github community project.

**Comment by stevepryde** [comment]
Sorry I don't have the time to contribute to this. All the best with it.
